### ISSUE TITLE
Misstatement in the "Interactions" lab in Section 28

### ISSUE THREAD

**Issue by witchlane** [learn-co-curriculum/dsc-interaction-terms#1]
Unless I am missing something, the circled statement below is incorrect.  It should read "Weight loss is bigger in the USA than the UK" not the other way around because all of the "mean of Weight Change" variables are all larger for the USA column.
![image](https://user-images.githubusercontent.com/44211854/61369058-3d934f80-a85d-11e9-8ea5-7593c18bece6.png)

**Comment by lmcm18** [comment]
Fixed.
