### ISSUE TITLE
Maybe a typo

### ISSUE THREAD

**Issue by plumkes** [learn-co-curriculum/dsc-interaction-terms#4]
In the second bullet-point under "What Are Interactions?" it says that the UK is responding well to diet A, but I think it might mean to say NZ is responding well to the diet.

**Comment by hoffm386** [comment]
Thanks for flagging! Corrected this in https://github.com/learn-co-curriculum/dsc-interaction-terms/commit/02aaf6a2c7b2c8f5ecd22499214c04498f762d3c
